import type { Program } from '../../data/types'

/**
 * Natali's research snapshot: September 2026, for a Winter Semester 2027/28 start.
 * English-taught electrical / electronics master's programs in Germany and Austria within
 * a €1,500-per-semester tuition budget. Deadlines are projected from the 2026/27 cycle.
 * Rankings: QS World University Rankings 2027. Semester fees are the WS 2026/27 amounts.
 */
const G = 'your GPA (2.88 → 3.0/4.0, roughly German 2.1 → 2.0)'
const TOP5 = 'Being in the top 5% of your class is a strong point: ask your faculty for a class-rank certificate and include it'

export const nataliPrograms: Program[] = [
  {
    id: 'rwth-epe',
    university: 'RWTH Aachen University',
    short: 'RWTH',
    program: 'Electrical Power Engineering',
    degree: 'M.Sc.',
    city: 'Aachen',
    state: 'North Rhine-Westphalia',
    coords: [50.7779, 6.0775],
    kind: 'TU9',
    color: '#00549f',
    focus: ['power', 'control'],
    tier: 'reach',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 5,
    difficultyNote: `Very competitive, and the GRE is mandatory for non-EU applicants: the faculty asks for a Quant score in the top 15% (85th percentile, roughly 165+) and Verbal above the 15th percentile. It also checks detailed credit minimums per subject. With ${G} it is a reach; a strong GRE and your class rank help most.`,
    fit: 78,
    fitNotes: [
      'Matches your interest in EVs and power electronics',
      'Includes an 18-week industrial internship inside the program, which is good for your CV',
      TOP5,
    ],
    gaps: [
      'The GRE is mandatory for non-EU degrees. Quant must be in the top 15% of test takers (85th percentile, roughly 165+)',
      'Since the latest reform, EPE is the English-taught specialisation of RWTH\'s M.Sc. Electrical Engineering, Information Technology and Computer Engineering',
      'Strict credit minimums: 28 ECTS maths, 10 physics/devices, 34 electrical fundamentals, 8 programming, 10 control/systems theory, 10 electromagnetic fields or information theory, 20 application courses. Send your curriculum so the app can check them',
      'Electromagnetic field theory is often missing from computer & electronics degrees, so check it',
    ],
    path: {
      score: 5,
      team: 'Ecurie Aix (electric + driverless Formula Student, founded 1999)',
      points: [
        'Large power electronics, electrical machines and e-mobility institutes',
        'E.ON Energy Research Center on campus',
      ],
    },
    ranking: { qsWorld: '#104', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 370, living: 950, appFee: 'None (direct application)' },
    application: {
      portal: 'RWTHonline',
      portalUrl: 'https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/bewerbung-um-einen-studienplatz/master-bewerbung/~dqml/bewerbung-master-internationale/?lidx=1',
      opens: '1 December',
      deadline: '2027-03-01',
      deadlineNote: 'RWTH\'s non-EU deadline for the winter semester is 1 March (summer: 1 September). Your GRE scores must reach RWTH (ETS code 8504) by then.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical engineering or equivalent', status: 'ok' },
      { label: 'Credits', value: 'Detailed minimums per subject (see "Watch out for")', status: 'warn', note: 'Needs your curriculum to check' },
      { label: 'GRE General', value: 'Required for non-EU degrees: Quant ≥ 85th percentile (≈ 165+), Verbal ≥ 15th percentile', status: 'todo' },
      { label: 'English', value: 'B2: TOEFL iBT 90 or IELTS 5.5', status: 'todo' },
      { label: 'German', value: 'Not required', status: 'ok' },
    ],
    extraDocs: ['Official GRE score report (ETS code 8504)'],
    highlights: ['English specialisation of RWTH\'s electrical engineering master', 'Strong in power electronics, drives and grids', '4 semesters, including an 18-week industrial internship'],
    photos: [
      { file: 'SuperC RWTH Aachen.JPG', caption: 'SuperC student service centre' },
      { file: 'RWTH Aachen Hauptgebäude.jpg', caption: 'RWTH main building' },
    ],
    links: [
      { label: 'Faculty 6: admission and requirements', url: 'https://www.elektrotechnik.rwth-aachen.de/go/id/qndx/lidx/1' },
      { label: 'International applicants (RWTH)', url: 'https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/bewerbung-um-einen-studienplatz/master-bewerbung/~dqml/bewerbung-master-internationale/?lidx=1' },
    ],
  },
  {
    id: 'kit-etit',
    university: 'Karlsruhe Institute of Technology (KIT)',
    short: 'KIT',
    program: 'Electrical Engineering and Information Technology',
    degree: 'M.Sc.',
    city: 'Karlsruhe',
    state: 'Baden-Württemberg',
    coords: [49.0106, 8.4125],
    kind: 'TU9',
    color: '#009682',
    focus: ['power', 'electronics', 'embedded', 'control', 'comms'],
    tier: 'reach',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 4,
    difficultyNote: `Since WS 2025/26 admission is restricted: applicants are ranked by how well their courses match and by their overall grade. With ${G} it is a reach, but your class rank and strong circuits/microprocessor grades help.`,
    fit: 85,
    fitNotes: ['Very broad: covers all five of your interests', 'Tuition €1,500 per semester is exactly at your limit', TOP5],
    gaps: ['Ranking uses your overall grade', 'Tuition is €1,500 per semester (Baden-Württemberg)'],
    path: {
      score: 4,
      team: 'KA-RaceIng (electric + driverless Formula Student)',
      points: ['Bosch, SEW-Eurodrive and EnBW are nearby employers for drives and power electronics', 'Large research centre with many student-job (HiWi) positions'],
    },
    ranking: { qsWorld: '#110', qsYear: 'QS 2027' },
    costs: { tuition: 1500, semesterFee: 190, living: 1000, appFee: 'None (direct application)' },
    application: {
      portal: 'KIT online application',
      portalUrl: 'https://www.etit.kit.edu/english/Application_Master_ETIT.php',
      opens: 'about mid-May',
      deadline: '2027-07-15',
      deadlineNote: 'Non-EU: 15 July for the winter semester (15 January for summer). The portal usually opens in mid-May. Apply early so the visa is not a problem.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical engineering / IT or related', status: 'ok' },
      { label: 'Selection', value: 'Ranking by course content and overall grade', status: 'warn' },
      { label: 'English', value: 'B2 (CEFR), proven by enrolment', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Taught in English', 'Top-3 German technical university', 'Wide choice of specialisations'],
    photos: [
      { file: 'Polytechnikum Karlsruhe.JPG', caption: 'Historic Polytechnikum, KIT Campus South' },
      { file: 'Otto-Ammann-Platz 1 Karlsruhe 2.JPG', caption: 'KIT Campus South' },
    ],
    links: [
      { label: 'Program page', url: 'https://www.sle.kit.edu/english/vorstudium/master-electrical-engineering-information-technology.php' },
      { label: 'How to apply (ETIT)', url: 'https://www.etit.kit.edu/english/Application_Master_ETIT.php' },
    ],
  },
  {
    id: 'stuttgart-infotech',
    university: 'University of Stuttgart',
    short: 'Stuttgart',
    program: 'Information Technology (INFOTECH)',
    degree: 'M.Sc.',
    city: 'Stuttgart (Vaihingen)',
    state: 'Baden-Württemberg',
    coords: [48.7456, 9.1057],
    kind: 'TU9',
    color: '#004191',
    focus: ['embedded', 'comms', 'electronics'],
    tier: 'reach',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 4,
    difficultyNote: `A long-running international program with limited places. Your bachelor's grade is the main selection criterion (the committee considers your university's grading), so with ${G} it is a reach. The class rank helps.`,
    fit: 88,
    fitNotes: ['Specialisations in embedded systems, communications and microelectronics: three of your interests in one program', 'Stuttgart has Bosch, Mercedes-Benz and Porsche: big employers for embedded and EV electronics', TOP5],
    gaps: ['Limited places, ranked by grade', 'Tuition is €1,500 per semester (Baden-Württemberg)'],
    path: {
      score: 5,
      team: 'GreenTeam Uni Stuttgart (electric + driverless Formula Student)',
      points: ['Bosch, Mercedes-Benz and Porsche are next door', 'Automotive electronics and embedded software jobs everywhere in the region'],
    },
    ranking: { qsWorld: '#318', qsYear: 'QS 2027' },
    costs: { tuition: 1500, semesterFee: 184, living: 1150, appFee: 'None via C@MPUS' },
    application: {
      portal: 'C@MPUS',
      portalUrl: 'https://www.infotech.uni-stuttgart.de/application/',
      opens: '15 November 2026',
      deadline: '2027-01-15',
      deadlineNote: 'INFOTECH\'s own calendar: 15 November – 15 January for the winter semester (15 May – 15 July is the summer-semester round). Admission letters come around April/May.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical engineering, IT or related', status: 'ok' },
      { label: 'Selection', value: 'Bachelor grade is the main criterion (admission-restricted)', status: 'warn' },
      { label: 'English', value: 'Good command of English (check the required score)', status: 'todo' },
      { label: 'German', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['One of Germany\'s oldest English-taught EE programs', 'Embedded systems, communications, microelectronics tracks', 'In the heart of the automotive industry'],
    photos: [
      { file: 'Universität Stuttgart (Vaihingen) 017.JPG', caption: 'Campus Vaihingen' },
      { file: 'Universität Stuttgart (Vaihingen) 003.JPG', caption: 'Campus Vaihingen' },
    ],
    links: [
      { label: 'INFOTECH', url: 'https://www.infotech.uni-stuttgart.de/' },
      { label: 'Application', url: 'https://www.infotech.uni-stuttgart.de/application/' },
      { label: 'Program page', url: 'https://www.uni-stuttgart.de/en/study/study-programs/Information-Technology-INFOTECH-M.Sc./' },
    ],
  },
  {
    id: 'fau-cme',
    university: 'FAU Erlangen-Nürnberg',
    short: 'FAU',
    program: 'Communications and Multimedia Engineering (CME)',
    degree: 'M.Sc.',
    city: 'Erlangen',
    state: 'Bavaria',
    coords: [49.5737, 11.03],
    kind: 'University',
    color: '#04316a',
    focus: ['comms', 'embedded'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 3,
    difficultyNote: 'An established English program with a large international cohort. Signal processing is your strongest subject, which fits the program exactly. IELTS 6.0 is enough, and FAU charges no tuition for this program (non-EU applicants pay a €100 processing fee).',
    fit: 90,
    fitNotes: ['Signal processing is your best subject, and this program is built around it', 'Your active-noise-cancellation project is a perfect topic for the motivation letter', 'You can apply before graduating; the final certificate is due by 30 September', TOP5],
    gaps: [],
    path: {
      score: 5,
      team: 'High-Voltage Motorsports (FAU\'s Formula Student team, fully electric since 2022)',
      points: ['Fraunhofer IIS (the institute that invented MP3) is in Erlangen: the ideal place for audio and signal processing jobs', 'Erlangen is one of Siemens\' biggest sites'],
    },
    ranking: { qsWorld: '#218', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 82, living: 1000, appFee: '€100 processing fee (non-EU)' },
    application: {
      portal: 'FAU campo',
      portalUrl: 'https://www.cme.studium.fau.de/prospective-students/application-process/',
      opens: 'February 2027',
      deadline: '2027-07-15',
      deadlineNote: 'The campo portal is open from February until 15 July 2027 for the winter intake. Visa applicants should apply as early as possible.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical, communication or computer engineering (or similar)', status: 'ok' },
      { label: 'English', value: 'IELTS 6.0 / TOEFL iBT 80 (B2)', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Signal processing, communications and multimedia', 'Fraunhofer IIS in town', 'No tuition fees'],
    photos: [
      { file: 'FAU Engineering East 01.JPG', caption: 'FAU Faculty of Engineering' },
      { file: 'EEI FAU Erlangen.jpg', caption: 'Electrical engineering building' },
    ],
    links: [
      { label: 'CME program', url: 'https://www.cme.studium.fau.de/' },
      { label: 'Application process', url: 'https://www.cme.studium.fau.de/prospective-students/application-process/' },
      { label: 'FAU program page', url: 'https://www.fau.eu/degree-program/communications-and-multimedia-engineering-cme-m-sc/' },
    ],
  },
  {
    id: 'tud-nano',
    university: 'TU Dresden',
    short: 'TU Dresden',
    program: 'Nanoelectronic Systems',
    degree: 'M.Sc.',
    city: 'Dresden',
    state: 'Saxony',
    coords: [51.0284, 13.7267],
    kind: 'TU9',
    color: '#00305d',
    focus: ['electronics'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 3,
    difficultyNote: 'Admission goes through an aptitude assessment that checks your subject background: maths, analogue and digital circuit design, electromagnetic fields, systems theory, electronic devices and programming. One of these may be missing. Your circuits grades are a strength.',
    fit: 82,
    fitNotes: ['Analogue and digital circuits are among your best subjects', 'Dresden is Europe\'s biggest microelectronics hub ("Silicon Saxony")', 'No tuition fees and low living costs'],
    gaps: ['Check electromagnetic fields and systems theory in your curriculum', 'IELTS 6.5 required'],
    path: {
      score: 5,
      team: 'Elbflorace (electric Formula Student)',
      points: ['Infineon, GlobalFoundries and Bosch run chip fabs in Dresden, and a new TSMC joint-venture fab (ESMC) is being built', 'Excellent for a microelectronics career'],
    },
    ranking: { qsWorld: '#185', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 361, living: 850, appFee: 'uni-assist: €75' },
    application: {
      portal: 'uni-assist',
      portalUrl: 'https://tu-dresden.de/ing/elektrotechnik/studium/im_studium/studiengaenge/masters-programme-nanoelectronic-systems/prospective-students/bewerbung',
      opens: 'spring',
      deadline: '2027-07-15',
      deadlineNote: 'Deadline 15 July. Applicants with a foreign degree apply through uni-assist, so submit a few weeks earlier to leave time for the document check.',
      viaUniAssist: true,
    },
    requirements: [
      { label: 'Degree', value: 'Electrical engineering, information systems, computer science, physics or equivalent', status: 'ok' },
      { label: 'Aptitude assessment', value: 'Subject background checked (one area may be missing)', status: 'warn', note: 'Send your curriculum to check' },
      { label: 'English', value: 'IELTS 6.5 / TOEFL iBT 94', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Microelectronics and nanoelectronics', 'In "Silicon Saxony"', 'Affordable city'],
    photos: [
      { file: 'Technikum TU Dresden Werner-Hartmann-Bau 2013.JPG', caption: 'Werner-Hartmann-Bau (microelectronics)' },
      { file: '2016-04-14 Hörsaalzentrum TU Dresden by DCB.jpg', caption: 'Lecture hall centre' },
    ],
    links: [
      { label: 'Admission requirements', url: 'https://tu-dresden.de/ing/elektrotechnik/studium/im_studium/studiengaenge/masters-programme-nanoelectronic-systems/prospective-students/admission-requirements' },
      { label: 'Application', url: 'https://tu-dresden.de/ing/elektrotechnik/studium/im_studium/studiengaenge/masters-programme-nanoelectronic-systems/prospective-students/bewerbung' },
    ],
  },
  {
    id: 'tuhh-mms',
    university: 'Hamburg University of Technology (TUHH)',
    short: 'TUHH',
    program: 'Microelectronics and Microsystems',
    degree: 'M.Sc.',
    city: 'Hamburg',
    state: 'Hamburg',
    coords: [53.4601, 9.9696],
    kind: 'Technical University',
    color: '#2d9cdb',
    focus: ['electronics', 'embedded'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 3,
    difficultyNote: 'Requires an electrical engineering bachelor plus subject-specific requirements. You can apply to only ONE international master\'s program at TUHH, so choose carefully.',
    fit: 82,
    fitNotes: ['Circuits and microprocessors are your best subjects', 'No tuition fees'],
    gaps: ['Only one international master application allowed at TUHH', 'IELTS 6.5 required (certificate ≤ 2 years old)'],
    path: {
      score: 3,
      team: 'e-gnition Hamburg (electric + driverless)',
      points: ['NXP Semiconductors has a large site in Hamburg', 'Aerospace electronics (Airbus)'],
    },
    ranking: { qsWorld: '721–730', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 400, living: 1150, appFee: 'Check the TUHH "How to apply" PDF' },
    application: {
      portal: 'TUHH online application',
      portalUrl: 'https://www.tuhh.de/tuhh/en/studying/before-studying/degree-courses/international-study-programs/microelectronics-and-microsystems',
      opens: '1 December',
      deadline: '2027-02-01',
      deadlineNote: 'The pre-check (a GPA check) opens on 1 December. Sources give 1 February or 1 March as the closing date, so plan for 1 February.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical engineering + subject requirements', status: 'warn', note: 'Check the subject list against your curriculum' },
      { label: 'English', value: 'IELTS 6.5 / TOEFL iBT 90', status: 'todo' },
      { label: 'Limit', value: 'One international master application per applicant', status: 'warn' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Chip design and microsystems', 'Tuition-free', 'Big international city'],
    photos: [
      { file: 'Hauptgebäude der Technischen Universität der Freien und Hansestadt Hamburg.JPG', caption: 'TUHH main building' },
      { file: 'TUHH, Hamburg, Germany, Library.jpeg', caption: 'University library' },
    ],
    links: [
      { label: 'Program page', url: 'https://www.tuhh.de/tuhh/en/studying/before-studying/degree-courses/international-study-programs/microelectronics-and-microsystems' },
      { label: 'Admission requirements', url: 'https://www.tuhh.de/tuhh/en/studying/before-studying/degree-courses/international-study-programs/microelectronics-and-microsystems/admission-requirements' },
    ],
  },
  {
    id: 'rptu-esy',
    university: 'RPTU Kaiserslautern-Landau',
    short: 'RPTU',
    program: 'Embedded Computing Systems (ESY)',
    degree: 'M.Sc.',
    city: 'Kaiserslautern',
    state: 'Rhineland-Palatinate',
    coords: [49.4245, 7.7528],
    kind: 'Technical University',
    color: '#507289',
    focus: ['embedded', 'control'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 3,
    difficultyNote: 'An English embedded-systems program in the electrical & computer engineering department. The same department also offers Automation and Control (A&C) in English. Documents are assessed individually, so your projects count.',
    fit: 88,
    fitNotes: ['Your ATmega Gameboy, sumo robot and FPGA work are exactly embedded systems', 'Fraunhofer IESE (embedded software) is on campus', 'Tuition-free, low living costs'],
    gaps: ['IELTS 6.5 required'],
    path: {
      score: 4,
      team: 'KaRaT, Kaiserslautern Racing Team (electric Formula Student)',
      points: ['Fraunhofer IESE (embedded software) and DFKI (German AI research centre) in Kaiserslautern'],
    },
    ranking: { qsWorld: '1401+', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 382, living: 850, appFee: '€60 assessment fee' },
    application: {
      portal: 'RPTU EIT application portal',
      portalUrl: 'https://applymsc.eit.rptu.de/',
      opens: '1 November',
      deadline: '2027-04-30',
      deadlineNote: 'International applicants: 1 November – 30 April for the winter semester. RPTU starts evaluating after the deadline, once the €60 fee has arrived.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical/computer engineering or related', status: 'ok' },
      { label: 'English', value: 'IELTS 6.5 / TOEFL iBT 81', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Embedded systems focus', 'Automation & Control is a second English option', 'Can apply with a current transcript'],
    photos: [{ file: 'TU Kaiserslautern - Campus und Audimax.jpg', caption: 'Campus and Audimax' }],
    links: [
      { label: 'Master in English (EIT)', url: 'https://eit.rptu.de/en/studies/master-in-english' },
      { label: 'ESY admission', url: 'https://eit.rptu.de/en/esy/admission' },
      { label: 'Application portal', url: 'https://applymsc.eit.rptu.de/' },
    ],
  },
  {
    id: 'ude-ese',
    university: 'University of Duisburg-Essen (UDE)',
    short: 'UDE',
    program: 'Embedded Systems Engineering (ISE)',
    degree: 'M.Sc.',
    city: 'Duisburg',
    state: 'North Rhine-Westphalia',
    coords: [51.4281, 6.7995],
    kind: 'University',
    color: '#004c93',
    focus: ['embedded', 'electronics'],
    tier: 'safety',
    language: 'English + German (ISE: about 50% of lectures in German)',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 2,
    difficultyNote: 'Part of UDE\'s long-running international ISE programs, with moderate admission. A realistic safety option with your profile.',
    fit: 85,
    fitNotes: ['Embedded systems matches your microcontroller and FPGA experience', 'Fraunhofer IMS (microelectronic circuits) is in Duisburg', 'Tuition-free'],
    gaps: ['About half the lectures are in German, and German B2 must be proven (the certificate can follow after the application). You have B1, so plan to reach B2 by October 2027', 'ISE applications go through the UDE portal. Non-restricted programs close on 31 July, restricted ones on 15 June, so plan for 15 June'],
    path: {
      score: 3,
      team: 'E-Team Duisburg-Essen (electric Formula Student)',
      points: ['Fraunhofer IMS (microelectronic circuits and systems) in Duisburg'],
    },
    ranking: { qsWorld: '801–850', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 368, living: 900, appFee: 'Check the UDE portal' },
    application: {
      portal: 'UDE application portal (ISE)',
      portalUrl: 'https://www.uni-due.de/international/international-admissions-en.php',
      opens: '1 May',
      deadline: '2027-06-15',
      deadlineNote: 'Non-EU window for the winter semester: 1 May – 15 June for admission-restricted programs, until 31 July otherwise. Plan for 15 June.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical/computer engineering or related', status: 'ok' },
      { label: 'English', value: 'B2 or higher (check the exact score)', status: 'todo' },
      { label: 'German', value: 'B2 at enrolment (~50% of lectures in German)', status: 'warn', note: 'You have B1' },
      { label: 'Credits', value: 'First degree of at least 210 ECTS', status: 'ok', note: 'You will have 240' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['International ISE program (English + German)', 'Ruhr area: affordable, lots of industry', 'Winter and summer intake'],
    photos: [{ file: 'Uni DuE Duisburg LE1.JPG', caption: 'Campus Duisburg' }],
    links: [
      { label: 'International admissions', url: 'https://www.uni-due.de/international/international-admissions-en.php' },
      { label: 'Program on DAAD', url: 'https://www.daad.de/en/studying-in-germany/universities/all-degree-programmes/detail/university-of-duisburg-essen-embedded-systems-engineering-ise-w48523/?hec-id=w48523' },
    ],
  },
  {
    id: 'chemnitz-es',
    university: 'Chemnitz University of Technology',
    short: 'TU Chemnitz',
    program: 'Embedded Systems',
    degree: 'M.Sc.',
    city: 'Chemnitz',
    state: 'Saxony',
    coords: [50.8132, 12.9296],
    kind: 'Technical University',
    color: '#005f50',
    focus: ['embedded', 'electronics'],
    tier: 'safety',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 2,
    difficultyNote: 'Expects strong basics in hardware (op-amps, signal processing, microcontroller architectures) and C/C++, which is exactly your profile. Moderate admission; a safety option.',
    fit: 88,
    fitNotes: ['Asks for op-amps, signal processing, microcontrollers and C/C++: all things you have done', 'German A1 is required and you have B1', 'Cheapest city on the list, and tuition-free'],
    gaps: ['Apply through uni-assist', 'The German certificate must come from Goethe, telc or ÖSD, and it is needed with the application'],
    path: {
      score: 3,
      team: 'Check the current Formula Student team list',
      points: ['Fraunhofer ENAS (smart systems) and a strong automotive-electronics region'],
    },
    ranking: { qsWorld: '1001–1200', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 341, living: 800, appFee: 'uni-assist: €75' },
    application: {
      portal: 'uni-assist',
      portalUrl: 'https://www.tu-chemnitz.de/etit/studium/stugang/index.php.en?page=m_es',
      opens: '1 April',
      deadline: '2027-07-15',
      deadlineNote: 'Non-EU degrees: 15 July for the winter semester, through uni-assist (applications open 1 April). Apply early to leave time for the document check.',
      viaUniAssist: true,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in ICT, electrical engineering or equivalent', status: 'ok' },
      { label: 'English', value: 'B2', status: 'todo' },
      { label: 'German', value: 'A1 certificate with the application (Goethe, telc or ÖSD), A2 by the end of the 3rd semester', status: 'ok', note: 'You have B1. Make sure you have the certificate' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: ['uni-assist application'],
    highlights: ['Hardware + software embedded systems', 'Very affordable', 'Two intakes a year'],
    photos: [
      { file: 'TU Chemnitz.JPG', caption: 'TU Chemnitz' },
      { file: 'Turmbau, TU Chemnitz, Reichenhainer Str (Barras).JPG', caption: 'Reichenhainer Straße campus' },
    ],
    links: [
      { label: 'Program page', url: 'https://www.tu-chemnitz.de/etit/studium/stugang/index.php.en?page=m_es' },
      { label: 'Application guide (PDF)', url: 'https://www.tu-chemnitz.de/studierendenservice/zsb/broschueren/Application_Guide_english_bf.pdf' },
    ],
  },
  {
    id: 'ilmenau-csp',
    university: 'TU Ilmenau',
    short: 'TU Ilmenau',
    program: 'Communications and Signal Processing',
    degree: 'M.Sc.',
    city: 'Ilmenau',
    state: 'Thuringia',
    coords: [50.6841, 10.9331],
    kind: 'Technical University',
    color: '#00a4a6',
    focus: ['comms'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter',
    difficulty: 3,
    difficultyNote: 'A specialised signal-processing program. The main hurdle is English: C1 is required for everyone, so aim for IELTS 7.0.',
    fit: 86,
    fitNotes: ['Signal processing is your strongest subject', 'Fraunhofer IDMT (audio and media technology) is in Ilmenau, a great match for your noise-cancellation project', 'Tuition-free, small university town'],
    gaps: ['English C1 required (IELTS ≈ 7.0)'],
    path: {
      score: 3,
      team: 'Check the current student team list',
      points: ['Fraunhofer IDMT (digital media / audio signal processing) on campus'],
    },
    ranking: { qsWorld: 'n/a', qsYear: 'QS', note: 'Check the current QS table' },
    costs: { tuition: 0, semesterFee: 332, living: 800, appFee: '€25 (TU Ilmenau portal) or €75 via uni-assist' },
    application: {
      portal: 'TU Ilmenau online application',
      portalUrl: 'https://www.tu-ilmenau.de/en/university/departments/department-of-electrical-engineering-and-information-technology/profile/institutes-and-groups/communications-engineering-group/master-of-science-in-communications-and-signal-processing/application',
      opens: 'spring',
      deadline: '2027-05-15',
      deadlineNote: '15 May for applicants from outside Europe.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical, communications or information engineering (or related)', status: 'ok' },
      { label: 'English', value: 'C1 (required even if the bachelor was in English)', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Pure communications and signal processing', 'Fraunhofer IDMT on campus', 'Quiet, cheap university town'],
    photos: [
      { file: 'Campus TU Ilmenau.jpg', caption: 'Campus TU Ilmenau' },
      { file: 'TU Ilmenau Helmholtzbau.JPG', caption: 'Helmholtzbau' },
    ],
    links: [
      { label: 'Program page', url: 'https://www.tu-ilmenau.de/en/study/before-the-study/range-of-courses/master/communications-and-signal-processing-msc' },
      { label: 'Application', url: 'https://www.tu-ilmenau.de/en/university/departments/department-of-electrical-engineering-and-information-technology/profile/institutes-and-groups/communications-engineering-group/master-of-science-in-communications-and-signal-processing/application' },
    ],
  },
  {
    id: 'paderborn-ese',
    university: 'Paderborn University',
    short: 'Paderborn',
    program: 'Electrical Systems Engineering',
    degree: 'M.Sc.',
    city: 'Paderborn',
    state: 'North Rhine-Westphalia',
    coords: [51.7071, 8.7718],
    kind: 'University',
    color: '#1d3d6e',
    focus: ['power', 'electronics', 'control', 'comms'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 3,
    difficultyNote: `Requires an overall grade of 2.5 or better (German scale). ${G[0].toUpperCase() + G.slice(1)} meets that. Non-EU applicants must take the GRE and include the results (Quant ≥ 157 and Writing 4.0 are desirable; very good grades can make up for a weaker score).`,
    fit: 84,
    fitNotes: ['Broad: power electronics, circuits, control and communications', 'The grade minimum of 2.5 is met', 'Tuition-free'],
    gaps: ['GRE needed for non-EU applicants (Q 157+, AW 4.0 desirable)', 'Required: ≥ 24 ECTS advanced maths, ≥ 4 signal theory, ≥ 4 systems theory, ≥ 5 field theory. Check field theory'],
    path: {
      score: 3,
      team: 'UPBracing Team (Formula Student)',
      points: ['Heinz Nixdorf Institute (intelligent technical systems)', 'FORVIA HELLA, a big automotive-electronics supplier, is in nearby Lippstadt'],
    },
    ranking: { qsWorld: '1201–1400', qsYear: 'QS 2027' },
    costs: { tuition: 0, semesterFee: 351, living: 900, appFee: 'uni-assist: €75' },
    application: {
      portal: 'uni-assist',
      portalUrl: 'https://www.uni-paderborn.de/en/studies/international-office/degree-students/application-for-admission-terms/application-deadlines',
      opens: 'spring',
      deadline: '2027-05-30',
      deadlineNote: 'The ESE page gives 30 May and the university\'s general page 31 May, so plan for 30 May. Extra documents (e.g. the language certificate) can follow until 15 July.',
      viaUniAssist: true,
    },
    requirements: [
      { label: 'Degree', value: 'Electrical engineering bachelor with maths, signal, systems and field theory', status: 'warn', note: 'Check field theory in your curriculum' },
      { label: 'Grade', value: '2.5 or better (German scale)', status: 'ok' },
      { label: 'GRE', value: 'Required for non-EU (Q ≥ 157, AW 4.0 desirable)', status: 'todo' },
      { label: 'English', value: 'IELTS 6.0 or TOEFL iBT 80', status: 'todo' },
    ],
    extraDocs: ['GRE score report', 'uni-assist application'],
    highlights: ['Broad electrical engineering in English', 'Fixed grade minimum that you meet', 'Affordable city'],
    photos: [],
    links: [
      { label: 'Program page', url: 'https://www.uni-paderborn.de/en/studyoffer/course_of_study/electrical-systems-engineering-english-taught-program-master' },
      { label: 'Department page', url: 'https://ei.uni-paderborn.de/en/studies/degree-program/electrical-systems-engineering' },
      { label: 'Deadlines', url: 'https://www.uni-paderborn.de/en/studies/international-office/degree-students/application-for-admission-terms/application-deadlines' },
    ],
  },
  {
    id: 'deggendorf-eeit',
    university: 'Deggendorf Institute of Technology (DIT)',
    short: 'DIT',
    program: 'Electrical Engineering and Information Technology',
    degree: 'M.Sc.',
    city: 'Deggendorf',
    state: 'Bavaria',
    coords: [48.8317, 12.9546],
    kind: 'University of Applied Sciences',
    color: '#0a5c8c',
    focus: ['electronics', 'embedded', 'control'],
    tier: 'safety',
    language: 'English',
    semesters: 3,
    intake: 'Winter & summer',
    difficulty: 2,
    difficultyNote: 'A practical, English-only program at a university of applied sciences. Less competitive than the TU9 universities; a safety option.',
    fit: 80,
    fitNotes: ['Hands-on style suits your project-heavy profile', 'Your 240 ECTS bachelor fits the 90-ECTS, 3-semester master'],
    gaps: ['Since WS 2025/26 DIT charges non-EU students a €500 service fee per semester', 'There is an aptitude test'],
    path: {
      score: 2,
      team: 'Check the current student team list',
      points: ['Continental and Infineon have large sites in the Regensburg region'],
    },
    ranking: { qsWorld: 'Not ranked', qsYear: 'QS', note: 'QS does not rank universities of applied sciences' },
    costs: { tuition: 500, semesterFee: 82, living: 900, appFee: '€60 application fee' },
    application: {
      portal: 'DIT application portal',
      portalUrl: 'https://www.mygermanuniversity.com/master/electrical-engineering-and-information-technology/394',
      opens: '15 April',
      deadline: '2027-06-15',
      deadlineNote: 'Application period for the October start: 15 April – 15 June. Upload everything online; nothing needs to be posted.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Bachelor in electrical engineering / IT or related', status: 'ok' },
      { label: 'English', value: 'B2 (e.g. IELTS or TOEFL)', status: 'todo' },
      { label: 'Aptitude test', value: 'Required (no NC)', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: [],
    highlights: ['Practical M.Sc., 3 semesters', 'Two intakes a year', 'No NC: admission by aptitude test'],
    photos: [],
    links: [{ label: 'Program overview', url: 'https://www.mygermanuniversity.com/master/electrical-engineering-and-information-technology/394' }],
  },
  {
    id: 'tuwien-ecs',
    university: 'TU Wien',
    short: 'TU Wien',
    program: 'Embedded Computing Systems',
    degree: 'M.Sc.',
    city: 'Vienna',
    state: 'Vienna',
    country: 'Austria',
    coords: [48.199, 16.3699],
    kind: 'Technical University',
    color: '#006699',
    focus: ['embedded', 'electronics'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 3,
    difficultyNote: 'Admission is an individual check that your bachelor has at least 120 ECTS in maths, computer science and electrical engineering at TU Wien level. It is not a grade ranking, so your GPA matters less here. You may be asked to take supplementary exams.',
    fit: 88,
    fitNotes: ['Circuit design + embedded + cyber-physical systems: a direct match', 'Not ranked by grade, which suits your profile', 'Vienna is a big, international capital'],
    gaps: ['Possible supplementary exams if parts of your degree don\'t match', 'IELTS 6.5 required'],
    path: {
      score: 4,
      team: 'TU Wien Racing (Formula Student) · TU Wien Space Team (rockets and satellites)',
      points: ['The Space Team is a natural home for your CubeSat ADCS project'],
    },
    ranking: { qsWorld: '#191', qsYear: 'QS 2027' },
    costs: { tuition: 727, semesterFee: 25, living: 1150, appFee: 'Check the admission page' },
    application: {
      portal: 'TU Wien admission (TISS)',
      portalUrl: 'https://www.tuwien.at/en/studies/admission/masters-programmes',
      opens: 'spring',
      deadline: '2027-07-31',
      deadlineNote: 'TU Wien advises having all documents at the Admissions Office by the end of July for an October start: processing takes 12–14 weeks. The formal period runs later, but the Austrian residence permit also takes time.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: '≥ 120 ECTS in maths, computer science and electrical engineering, incl. ≥ 24 maths, ≥ 12 programming, ≥ 16 electrical fundamentals', status: 'warn', note: 'Individual assessment. Send your curriculum to check' },
      { label: 'English', value: 'B2: IELTS 6.5 / TOEFL iBT 87', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: ['Proof of funds for the Austrian residence permit'],
    highlights: ['Taught in English', 'Joint program of the informatics and EE faculties', 'Tuition €726.72 per semester for non-EU'],
    photos: [
      { file: 'Wien - Techn. Universität, Institutsgebäude „Freihaus“.JPG', caption: 'Freihaus, TU Wien' },
      { file: 'TU Wien Freihaus Sept 2020 1.jpg', caption: 'Freihaus' },
    ],
    links: [
      { label: 'Program page', url: 'https://www.tuwien.at/en/studies/studies/master-programmes/embedded-computing-systems' },
      { label: 'English requirements', url: 'https://www.tuwien.at/en/studies/admission/masters-programmes/other-inter-national-bachelors-degree/competence-in-english' },
      { label: 'Tuition fee', url: 'https://www.tuwien.at/en/studies/admission/students-union-fee-and-tuition-fee/tuition-fee' },
    ],
  },
  {
    id: 'tugraz-ee',
    university: 'Graz University of Technology (TU Graz)',
    short: 'TU Graz',
    program: 'Electrical and Electronics Engineering',
    degree: 'M.Sc.',
    city: 'Graz',
    state: 'Styria',
    country: 'Austria',
    coords: [47.0587, 15.46],
    kind: 'Technical University',
    color: '#e4154b',
    focus: ['power', 'electronics', 'control'],
    tier: 'target',
    language: 'English',
    semesters: 4,
    intake: 'Winter & summer',
    difficulty: 3,
    difficultyNote: 'TU Graz\'s fully English-taught electrical master, with five majors including Electronic Systems & IC Design, Power Engineering and Wireless/Communication Systems. English must be C1 (aim for IELTS 7.0).',
    fit: 84,
    fitNotes: ['Graz is an EV and powertrain hub (AVL List), matching your e-mobility interest', 'Infineon, NXP and ams-OSRAM have development centres around Graz', 'TU Graz built Austria\'s first satellite (TUGSAT-1), relevant to your CubeSat project'],
    gaps: ['English C1 required: IELTS 7.0 or TOEFL iBT 95, no more than 2 years old', 'Apply early: the Austrian residence permit takes time', 'Some TU Graz English master\'s programs (e.g. Information and Computer Engineering) have an admission procedure with registration a year ahead, 15 October – 15 December. Check before 15 December 2026 whether this program is on that list'],
    path: {
      score: 5,
      team: 'TU Graz Racing Team (Formula Student)',
      points: ['AVL List (powertrain and e-mobility) is headquartered in Graz', 'Infineon, NXP and ams-OSRAM nearby'],
    },
    ranking: { qsWorld: '#409', qsYear: 'QS 2027' },
    costs: { tuition: 727, semesterFee: 25, living: 1000, appFee: 'Check the admission page' },
    application: {
      portal: 'TU Graz admission (by post/online)',
      portalUrl: 'https://www.tugraz.at/en/studying-and-teaching/studying-at-tu-graz/prospective-students/registration-and-admission/admission-of-international-degree-programme-applicants/overview-admission-of-international-degree-programme-applicants',
      opens: 'spring',
      deadline: '2027-09-05',
      deadlineNote: '5 September is TU Graz\'s recommended submission date for international applicants. Processing takes weeks to months and the residence permit takes longer, so apply in spring.',
      viaUniAssist: false,
    },
    requirements: [
      { label: 'Degree', value: 'Relevant bachelor in electrical engineering', status: 'ok' },
      { label: 'English', value: 'C1: IELTS 7.0 / TOEFL iBT 95 / Cambridge C1 Advanced 180', status: 'todo' },
      { label: 'GRE', value: 'Not required', status: 'ok' },
    ],
    extraDocs: ['Proof of funds for the Austrian residence permit'],
    highlights: ['Fully English, five majors', 'AVL, Infineon, NXP, ams-OSRAM nearby', 'Tuition €726.72 per semester for non-EU'],
    photos: [],
    links: [
      { label: 'Program page', url: 'https://www.tugraz.at/en/studying-and-teaching/degree-and-certificate-programmes/masters-degree-programmes/electrical-and-electronics-engineering' },
      { label: 'International admission', url: 'https://www.tugraz.at/en/studying-and-teaching/studying-at-tu-graz/prospective-students/registration-and-admission/admission-of-international-degree-programme-applicants/overview-admission-of-international-degree-programme-applicants' },
      { label: 'English requirements', url: 'https://www.tugraz.at/en/studying-and-teaching/studying-at-tu-graz/prospective-students/registration-and-admission/admission-of-international-degree-programme-applicants/proof-of-english-language-competence' },
      { label: 'Admission periods', url: 'https://www.tugraz.at/en/studying-and-teaching/studying-at-tu-graz/prospective-students/registration-and-admission/admission-periods' },
    ],
  },
]
